import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { Button } from "@/components/ui/button";
import { requireRole, roleHome } from "@/lib/auth/session";
import {
  countUnreadNotifications,
  listNotifications,
  notificationView,
} from "@/lib/notifications/query";
import { NotificationInbox } from "@/components/notifications/notification-inbox";

export const metadata: Metadata = {
  title: "Notifications",
};

export default async function NotificationsPage() {
  const user = await requireRole(["RESIDENT", "OFFICIAL", "ADMIN"]);

  const [notifications, unreadCount] = await Promise.all([
    listNotifications(user.id, { unread: false, concernId: null, limit: 100 }),
    countUnreadNotifications(user.id),
  ]);

  return (
    <Container className="py-8">
      <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Notifications</h1>
          <p className="mt-1 text-sm text-slate-600">
            Updates generated by real activity on your concerns and cases.
          </p>
        </div>
        <Button href={roleHome(user.role.key)} variant="outline" size="sm">
          Back to dashboard
        </Button>
      </div>

      <NotificationInbox
        notifications={notifications.map(notificationView)}
        unreadCount={unreadCount}
        role={user.role.key}
      />
    </Container>
  );
}
